version: '3'
services:
  db:
    image: postgres
    container_name: db
    env_file:
      - ./.env
    ports:
      - "${DATABASE_POSTGRES_INTERNAL_PORT}:${DATABASE_POSTGRES_EXTERNAL_PORT}"
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_POSTGRES_USER}
      - POSTGRES_PASSWORD=${DATABASE_POSTGRES_PASSWORD}
  pgadmin:
    image: fenglc/pgadmin4
    container_name: pgadmin
    env_file:
      - ./.env
    links:
      - db
    ports:
      - "${PGADMIN_PORT}:${PGADMIN_PORT}"
    environment:
      - DEFAULT_USER=${DEFAULT_PGADMIN_USER}
      - DEFAULT_PASSWORD=${DEFAULT_PGADMIN_PASSWORD}
  api:
    #build: .
    image: node:latest
    container_name: api
    env_file:
      - ./.env
    volumes:
      - ./server:/usr/api
    working_dir: /usr/api
    links:
      - db
    environment:
      - DATABASE_URL=${DATABASE_POSTGRES_URL}
    command: "npm run start-server"
    #command: "npm run start"
    ports:
      - "${BROWSERSYNC_PORT}:${BROWSERSYNC_PORT}"
      - "${DEBUG_PORT}:${DEBUG_PORT}"
      - "${API_PORT}:${API_PORT}"